In [3]:
import gym
import gym_ple

couldn't import doomish
Couldn't import doom


In [2]:
env = gym.make('CartPole-v1')
env.reset()

[2018-01-05 16:35:44,043] Making new env: CartPole-v1


array([ 0.00748947,  0.00293417, -0.02796376, -0.00261042])

In [3]:
print(env.action_space)

Discrete(2)


In [5]:
print(env.action_space.n)

2


In [ ]:
obs = env.reset()
print(type(obs))
print(obs.shape)

The four values we get are position, speed, angle, angular speed

In [2]:
import numpy as np
import numpy.ma as ma

In [48]:
a = np.random.random((10, 2))
print(a)
print(a.shape)

[[ 0.29402879  0.13234243]
 [ 0.57964609  0.5345744 ]
 [ 0.00448636  0.17591501]
 [ 0.04672698  0.78482824]
 [ 0.73767912  0.07878793]
 [ 0.72844225  0.13642737]
 [ 0.16089009  0.65050417]
 [ 0.66110837  0.59588406]
 [ 0.30337536  0.68977298]
 [ 0.56164314  0.72763459]]
(10, 2)


In [63]:
b = np.zeros((10), dtype='int8')
b[2] = 1
b[4] = 1
#b = b.reshape(-1, 1)
print(b)
print(b.shape)

[0 0 1 0 1 0 0 0 0 0]
(10,)


In [72]:
c = np.zeros(b.shape)
for i in range(len(a)):
    c[i] = a[i][b[i]]
print(c)
d = a[:, 0]*b
print(d)

[ 0.29402879  0.57964609  0.17591501  0.04672698  0.07878793  0.72844225
  0.16089009  0.66110837  0.30337536  0.56164314]
[ 0.          0.          0.00448636  0.          0.73767912  0.          0.
  0.          0.          0.        ]


In [68]:
np.max(a, 1)

array([ 0.29402879,  0.57964609,  0.17591501,  0.78482824,  0.73767912,
        0.72844225,  0.65050417,  0.66110837,  0.68977298,  0.72763459])

In [76]:
np.logical_not(b).astype('int8')

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1], dtype=int8)

In [83]:
t = (1, 'e')
tbis = (2, 'r')
print(t[1])
print(list(zip(*[t, tbis])))

e
[(1, 2), ('e', 'r')]


In [84]:
import mxnet.ndarray as nd

x = (1, 2, 4, 3)
print(nd.array(x))


[ 1.  2.  4.  3.]
<NDArray 4 @cpu(0)>


In [4]:
env = gym.make('FlappyBird-v0')
img = env.reset()
print(img.shape)

[2018-01-09 15:59:47,491] Making new env: FlappyBird-v0


(512, 288, 3)


In [1]:
from collections import deque

In [6]:
d = deque()

for i in range(5):
    d.append(np.random.random((6, 6)))

print(np.array(d).shape)
print(np.array(d).dtype)

(5, 6, 6)
float64
